org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Build environment ---------------------------------------------------------
version_minecraft=1.16.5
version_forge=36.2.34
# Parchment mappings for 1.16.5
version_parchment_mc=1.16.5
version_parchment=2022.03.06

# Immersive Engineering (host mod) ------------------------------------------
# IE CurseForge project id is 231951.
# File 3809596 is IE 1.16.5-5.1.0-148.
# Update curse_ie_file if you run a different IE build.
version_ie=1.16.5-5.1.0-148
curse_ie_project=231951
curse_ie_file=3809596

# Mod metadata --------------------------------------------------------------
mod_id=alternatingflux
mod_version=1.0.5
mod_group=antibluequirk.alternatingflux
mod_name=Alternating Flux
